import artimatic_operations as ao
(a,b)=5,3
print("The sum of {a} and {b} is:",ao.sum(a,b))
print("The difference of {a} and {b} is:",ao.subtract(a, b))
print("The product of {a} and {b} is:",ao.multiply(a, b))
print("The quotient of {a} and {b} is:",ao.divide(a, b))
print("The {a} raised to the power of {b} is:",ao.power(a, b))
print("The modulus of {a} and {b} is:",ao.modulus(a, b))
print("The floor division of {a} by {b} is:",ao.floor_divide(a, b))
print("The average of {a} and {b} is:",ao.average(a, b))
print("The maximum value between {a} and {b} is:",ao.max_value(a, b))
print("The minimum value between {a} and {b} is:",ao.min_value(a, b))
print("The absolute value of -{a} is:",ao.absolute(-a))
print("The square root of {a} is:",ao.square_root(a))
print("The cube root of {a} is:",ao.cube_root(a))
print("The factorial of {b} is:",ao.factorial(b))
print("The GCD of {a} and {b} is:",ao.gcd(a, b))
print("The LCM of {a} and {b} is:",ao.lcm(a, b))
print("The logarithm of {a} with base 10 is:",ao.logarithm(a))
print("The natural logarithm of {a} is:",ao.natural_log(a))
print("The exponential of {a} is:",ao.exponential(a))
print("The sine of {a} degrees is:",ao.sine(a))
print("The cosine of {a} degrees is:",ao.cosine(a))
print("The tangent of {a} degrees is:",ao.tangent(a))
print("The arcsine of {a}/10 is:",ao.arcsine(a/10))
print("The arccosine of {a}/10 is:",ao.arccosine(a/10))
print("The arctangent of {a} is:",ao.arctangent(a))
print("The hyperbolic sine of {a} is:",ao.hyperbolic_sine(a))
print("The hyperbolic cosine of {a} is:",ao.hyperbolic_cosine(a))
print("The hyperbolic tangent of {a} is:",ao.hyperbolic_tangent(a))